# Generated by Django 6.1.1 on 2026-10-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_manager",
            field=models.BooleanField(default=False, verbose_name="Менеджер"),
        ),
    ]
