[tool.poetry]
name = "mailing-service(cp4)"
version = "0.1.0"
description = ""
authors = ["Vladimir Rastorguev <vmrmozg138@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.14"
django = "^6.1.1"
pillow = "^12.3.0"
redis = "^8.1.0"
flake8 = "^7.4.1"
black = "^26.10.0"
isort = "^9.0.2"
mypy = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
