# Generated by Django 6.1.1 on 2026-10-07 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0002_distribution_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="distributions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Владелец",
            ),
            preserve_default=False,
        ),
    ]
