# Generated by Django 6.1.1 on 2026-10-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_service", "0005_alter_message_owner_alter_recipient_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="distribution",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активна"),
        ),
    ]
